################################################################################
# Project language
language: php
# Allows use container-based infrastructure
sudo: false
#sudo: required
dist: trusty

################################################################################
# Start mysql service
services:
  - mysql

################################################################################
# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

################################################################################
# Define an environment variable
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        
################################################################################
# Versions of PHP to test against
php:
#    - "5.6"
#    - "7.0"
    - "7.1"
    - "7.2"      

#################################################################################
## Prepare Test Environement
#before_install:
#    # Setup Travis PHP     
#    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
#    # Setup Composer Stability if Required   
#    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
#    # Setup Symfony Version if Required    
#    - if [ "$SF_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SF_VERSION; fi;
  
      
################################################################################
# Install composer dependencies,
# Create database, schema and fixtures
install:   
    # Update composer
    - composer self-update
    # With PHP < 7.1 => Remove Phpstan   
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove phpstan/phpstan-shim     --no-update --dev; fi      
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove phpstan/phpstan-phpunit  --no-update --dev; fi      
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove phpstan/phpstan-symfony  --no-update --dev; fi      
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove phpstan/phpstan-doctrine  --no-update --dev; fi      
    # Build Dependencies
    - composer update  --prefer-dist --no-interaction  

################################################################################
# Run script
script:
    # Execute Grump Travis Testsuite 
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP 7 => Execute Grump CsFixer Testsuite 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php vendor/bin/grumphp run --testsuite=csfixer; fi  
    # With PHP 7 => Execute Grump Phpstan Testsuite 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php vendor/bin/grumphp run --testsuite=phpstan; fi  
    
# After a build, send email notification with the build results
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always