
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
# You can to add host to /etc/hosts
#
# 172.169.1.10    	    sonata-admin.splashsync.local
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

name: Splash-Sonata-Admin

services:

    ################################################################################
    # Application Container
    app:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name:     sonata-admin.splashsync.local
        command:            sh /var/www/html/docker/docker-entrypoint.sh
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - COMPOSER_ROOT_VERSION=dev-master
        volumes:
            - ./:/var/www/html
            - ./docker/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            default:        { ipv4_address: 172.169.1.10, aliases: [ sonata-admin.splashsync.local ] }

    ################################################################################
    # PHP 8.2
    php-8.2:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.2
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - COMPOSER_ROOT_VERSION=dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php82:/var/www/html/vendor

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:              registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - COMPOSER_ROOT_VERSION=dev-master
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

volumes:
    vendor-php82: ~
    vendor-php81: ~

networks:
    ################################################################################
    # Default Private Network
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.169.1.0/24
