
################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
################################################################################

version: "3.5"

services:

    ################################################################################
    # PHP 8.1
    php-8.1:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
        container_name: splash-sonata-admin-8.1
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./:/var/www/html
            - vendor-php81:/var/www/html/vendor

    ################################################################################
    # PHP 8.0
    php-8.0:
        image:          registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
        container_name: splash-sonata-admin-8.0
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./:/var/www/html
            - vendor-php80:/var/www/html/vendor

    ################################################################################
    # Node JS Container
    node:
        image:              'node:18-alpine'
        user:               'node'
        container_name:     splash-sonata-admin-node
        tty:                true
        volumes:
            - './:/srv'
        working_dir: '/srv'

volumes:
    vendor-php81: ~
    vendor-php80: ~