
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ########################################################################
    # Splash Model Manager 
    Splash\Admin\Model\ObjectsManager:
        arguments: [ '@splash.connectors.manager', "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: splash.connectors.rename,   method: onObjectIdChangedEvent,  priority: 0 }   

    ################################################################################
    # AutoWire for Controllers
    Splash\Admin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments', 'container.service_subscriber']

    ################################################################################
    # AutoWire for Sonata Admin Filters
    Splash\Admin\Filter\:
        resource: '../../Filter'
        tags: ['sonata.admin.filter.type']

    ########################################################################
    # Render Fields View 
    splash.admin.twig.extension:
        class: Splash\Admin\Twig\SplashAdminExtension
        tags:   ["twig.extension"]

    ########################################################################
    # Event Listener to Catch Commit & Config Save Events
    splash.admin.subscriber:
        class: Splash\Admin\EventSubscriber\EventsSubscriber
        arguments: [ '@splash.connectors.manager', "@doctrine.orm.entity_manager" ]
        tags:       ["kernel.event_subscriber"]

    ########################################################################
    # Splash Admin Widgets Factory Service
    splash.admin.widget.factory:
        class: Splash\Admin\Services\WidgetFactoryService
        public: true
        arguments: 
            -   "@splash.widgets.factory"
            -   "@splash.connectors.manager"
