
services:
    
    ########################################################################
    # Splash Model Manager 
    sonata.admin.manager.splash:
        class: Splash\Admin\Model\ObjectsManager
        arguments: [ '@splash.connectors.manager', "@doctrine.orm.entity_manager" ]
        public: true

    ########################################################################
    # Render Fields View 
    splash.admin.twig.extension:
        class: Splash\Admin\Twig\SplashAdminExtension
        tags:   ["twig.extension"]

    ########################################################################
    # Event Listner to Catch Commit & Config Save Events 
    splash.admin.subscriber:
        class: Splash\Admin\EventSubscriber\EventsSubscriber
        arguments: [ '@splash.connectors.manager', "@doctrine.orm.entity_manager" ]
        tags:       ["kernel.event_subscriber"]

    ########################################################################
    # Splash Admin Widgets Factroy Service
    splash.admin.widget.factory:
        class: Splash\Admin\Services\WidgetFactoryService
        public: true
        arguments: 
            -   "@Splash.Widgets.Factory"
            -   "@splash.connectors.manager"
